name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: WindowsGrep

      - name: Build Application
        run: cargo build --release --manifest-path WindowsGrep/Cargo.toml

      - name: Run Tests
        run: cargo test --release --manifest-path WindowsGrep/Cargo.toml
